### ISSUE TITLE
Vagrant not working

### ISSUE THREAD

**Issue by Freakmania** [iptomar/projectary-api#11]
please review the vagrant file. bcrypt installation failing

**Comment by asantos3** [comment]
One of the solutions that some people recommend on stackoverflow is to use the [bcryptjs](https://www.npmjs.com/package/bcryptjs) package - slower and made in js though so it's not the optional solution.

**Comment by pauloagsantos** [comment]
follows this step.

1. upgrade virtual box and guest additions to last version
2. when run **vagrant up**, read the warnings, may by necessary to run **vagrant box update** first
3. when run **npm install** it exists some problems with bcrypt in virtualbox machines create on vagrant in windows machines. run first **npm install node-gyp -g** then **npm install bcrypt -g** and **finnaly npm install bcrypt -save**
4. run **npm install** just to confirm that is all ok
5. run **node main.js** 
6. see port forwardind issue

**Comment by asantos3** [comment]
This can be solved by doing a `vagrant up`, and `npm install`, on a shell with admin rights. It might be needed to delete the VM and create a new one.

Please test it on your end.

**Comment by asantos3** [comment]
There was a restructure on the repo, a new package.json without bcrypt and a new vagrantfile are up so closing this.
