### ISSUE TITLE
Symlink on windows gives error

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-api#13]
When doing `npm install` on projectary-api/PJ_API it gives this error:

> npm ERR! Linux 4.4.0-72-generic
> npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
> npm ERR! node v6.10.2
> npm ERR! npm  v3.10.10
> npm ERR! path ../mime/cli.js
> npm ERR! code EPROTO
> npm ERR! errno -71
> npm ERR! syscall symlink
> 
> npm ERR! EPROTO: protocol error, symlink '../mime/cli.js' -> '/vagrant/projectary-api/PJ_API/node_modules/.bin/mime'
> npm ERR!
> npm ERR! If you need help, you may report this error at:
> npm ERR!     <https://github.com/npm/npm/issues>
> 
> npm ERR! Please include the following file with any support request:
> npm ERR!     /vagrant/projectary-api/PJ_API/npm-debug.log

This can be solved by doing a `vagrant up`, and `npm install`, on a shell with admin rights or doing `node install --no-bin-links` - lacks confirmation for the first solution. Maybe document this kinda of errors somewhere?

**Comment by pauloagsantos** [comment]
but if you install without the binaries the bcrypt will not be installed

**Comment by asantos3** [comment]
> This can be solved by doing a `vagrant up`, and `npm install`, on a shell with admin rights

Confirming this works and it's the solution for running vagrant on windows hosts. It might be needed to delete the VM and create a new one.
This is also the solution for #11 and #12.

@secprog @jpcanoso @devlmarques Document this somewhere?

**Comment by asantos3** [comment]
Confirming that using a console with admin rights solves it
