### ISSUE TITLE
Foward port 3000 and 3001 from guest to host on Vagrantfile

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-api#20]
Right now there's no port forwarding for the frontend and when we start the frontend it uses port 3000 and 3001 so we should add it to the Vagrantfile:

> config.vm.network :forwarded_port, guest: 3000, host:3000
> config.vm.network :forwarded_port, guest: 3001, host:3001

I tested and saw no conflicts or errors.

**Comment by rui1974** [comment]
Done.
