### ISSUE TITLE
Login endpoint

### ISSUE THREAD

**Issue by davidbernardo** [iptomar/projectary-api#23]
The login endpoint is checking for authentication while trying to login, making it impossible due to the service checking if you are logged in to be able to log in.

**Comment by secprog** [comment]
I will check it but i think it sould be ok

**Comment by secprog** [comment]
Fixed with https://github.com/iptomar/projectary-api/commit/00c5dda4f7aaccb1d5deca9032c3aed56eccd87e commit and https://github.com/iptomar/projectary-frontend/pull/50 pull request
