### ISSUE TITLE
Group routes

### ISSUE THREAD

**Issue by diogosantosmendes** [iptomar/projectary-api#30]
Do you agree to use these routes for the groups?
![sem titulo](https://cloud.githubusercontent.com/assets/26015430/25776106/d11a4976-32ac-11e7-923e-0e3cec4a58be.png)

**Comment by jpcanoso** [comment]
Sorry for the lack of documentation. I've added a simple table on the [API Wiki](https://github.com/iptomar/projectary-api/wiki/API-Endpoints) with the existing routes.
The routes you posted will be like this:

| Method | Arguments | User | Description |
| --- | --- | --- | --- |
| GET | /GROUP | [ADMIN] | Get group's list |
| GET | /GROUP/:ID | [ADMIN] |Get a group |
| POST | /GROUP/CREATE | [USER] | Create a Group |
| POST | /GROUP/JOIN | [USER] | Join user to a Group |
| PUT | /GROUP/:ID | [ADMIN] | Update Group |
| DELETE | /GROUP/:ID | [ADMIN] | Delete Group |
