### ISSUE TITLE
Add mysql-testsuite package to Vagrantfile

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-api#38]
While developing a solution to test the database we concluded that we need the package `mysql-testsuite` from the repos so I'm requesting to add `sudo apt install mysql-testsuite` somewhere on the Vagrantfile.

**Comment by asantos3** [comment]
Uhm?

**Comment by secprog** [comment]
Sorry solved with commit https://github.com/iptomar/projectary-api/commit/7ab9755d5cda242aa934f6eed8da7a21537b077b
