### ISSUE TITLE
Users from a specific project

### ISSUE THREAD

**Issue by ghost** [iptomar/projectary-api#44]
According to some elements in the frontend group, the returned users associated to a project only returns one user even if there are more elements in the group.

This has been confirmed yesterday but since no one created an issue i decided to create it.

File in question
[Project.js](https://github.com/iptomar/projectary-api/blob/a8077b12e67108e5bf0cdbe9a3eba49afa0c187f/lib/routes/project.js#L72)

**Comment by secprog** [comment]
Fixed with pull request merge #45
