### ISSUE TITLE
Improve Vagrant documentation

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-api#48]
There's a few things you can do to improve the docs of Vagrant:
* Link to the files in the README - you can do that using the relative path.
* Wrongly formatted - you can see it [here](https://github.com/iptomar/projectary-api/blob/a17b3280fe68ee333bf74d776ec62648ac0d9b74/Vagrant_Readme.md). You need a space between the `-` and the text.
* Fix characters encoding - you can see that [here](https://raw.githubusercontent.com/iptomar/projectary-api/a17b3280fe68ee333bf74d776ec62648ac0d9b74/Vagrant_Readme.md), the encoding is borked up and probably the cause is the text editor badly configured.

@rui1974

**Comment by secprog** [comment]
Link to the files in the README - you can do that using the relative path.
If you can help with that will be great
I think that the others issues are solved

**Comment by jpcanoso** [comment]
In my opinion we should keep all the documention in the wiki, get rid of these files and use the readme.md to create links to the wiki, creating a better experience.

**Comment by asantos3** [comment]
Agreed, will wait for @rui1974 to link the wiki part of the vagrant in the readme and delete the .md files. Will close this when that is done.

**Comment by secprog** [comment]
Fixed with #55
