### ISSUE TITLE
install dependency mysql-testsuite on vagrant 

### ISSUE THREAD

**Issue by Freakmania** [iptomar/projectary-api#50]
this is used on database testing

**Comment by rui1974** [comment]
what version are you talking about ? tryied to install via sudo apt-get mysql-testsuite-5.7 and I get a message saying 5.7 is already the newest version. 0 upgraded, o newly installed, 0 to remove and 19 not upgraded

**Comment by jpcanoso** [comment]
I think that was fixed in #38 with 7ab9755

**Comment by asantos3** [comment]
True, I was next to him and we forgot to upgrade the Vagrantfile.
