### ISSUE TITLE
Add removed MD5 hashing

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-api#60]
Issue about it on the database: https://github.com/iptomar/projectary-bd/issues/132

The database shouldn't do the hashing and encryption of the passwords, the server/api should do it:
* You're wasting precious processing power on the database.
* The database has logs and will store some operations so sending passwords plain text is naive.
* If we want to move to something like bcrypt we would have problems on both sides - you can relate this with my first point and the lack of bcrypt or similar on mysql.

**Comment by secprog** [comment]
You are right Ok it will be done soon

**Comment by secprog** [comment]
Fixed
