### ISSUE TITLE
Passwords are not hashing correctly on student creation

### ISSUE THREAD

**Issue by ghost** [iptomar/projectary-api#65]
It seems passwords are being sent in plain text on user creation.
This seems to be caused by the async nature of this implementation of bcrypt.
I was able to fix the student creation here: https://github.com/iptomar/projectary-api/pull/64
but theres maybe some errors on the other routes aswell.

Edit:
Login is also broken.

**Comment by rui1974** [comment]
Don't know if this is of any help. This is from where I was trying to mod the code : 
It has async and sync methods
http://codetheory.in/using-the-node-js-bcrypt-module-to-hash-and-safely-store-passwords/

**Comment by secprog** [comment]
yup it is true i was lazy :( . i was almost 99% that will give problems. 
I didn't want to put that inside the callbacks. I gonna use the async module to fix that maybe or maybe i will just use the callbacks. yup there is also other routes that need to be fixed :)

**Comment by secprog** [comment]
i will fix this this afternoon

**Comment by rui1974** [comment]
ok, so, last test 20.00 "npm run frontend" from inside the api is showing some errors. Started from within frontend with "npm run start" worked well, however passwords beeing inserted in plain text. Wouldn't just hashing the email+password be easyier for now and avoiding collisions ?

**Comment by secprog** [comment]
Sorry I was a bit late I was in a presentation of Entrepreneurship I will do it now

**Comment by secprog** [comment]
@rui1974, @L0cust, @asantos3 Can you check. Everything sould be working now.

**Comment by rui1974** [comment]
No problem :) we all have other appointments, besides the app is working, this was more of an improvement. Unfortunately, still with errors. Not running the app, that works well either running it from the API or Frontend folders. However I get Server Error when trying to register a student. Maybe the endpoint / json package ?! 
![erro](https://user-images.githubusercontent.com/26015109/27614434-a66eb336-5b99-11e7-80df-12e3f2cb1a53.png)
![erro1](https://user-images.githubusercontent.com/26015109/27614481-ed9c9cf0-5b99-11e7-8fd7-bc16f6042bc1.png)

**Comment by rui1974** [comment]
P.S. Dropdowns do not get filled !

**Comment by secprog** [comment]
uhh strange I will clone the projetary-frontend and the api. It could be someting just missing like a import or something. I gonna check when I got sure that everything works I will ask you to test again . You got an error about cross zone connection maybe the cors is not working.

**Comment by ghost** [comment]
Tested just now, Login still doesn't work. :(

**Comment by secprog** [comment]
Yes I know i am working on it right now

**Comment by secprog** [comment]
Fixed login please test other functionality don't forget to activate the user in db manually.
Because other credentials stored on database now will not work.
@L0cust @rui1974

**Comment by secprog** [comment]
@rui1974 The problem of dropdown do not get filled is because you are using edge. Use another browser.

**Comment by secprog** [comment]
Passwords are now being hashed properly. I will close this issue. Related questions please use issue #63
