### ISSUE TITLE
Usar o yarn e incluir a instalação no vagrant

### ISSUE THREAD

**Issue by asantos3** [iptomar/projectary-api#8]
Isto é mais **uma sugestão** do que outra coisa e tem de ser discutido por todos mas já agora - @rui1974 e @apocas.

Podia-se usar o yarn em favor ao npm, ou pelo menos vir já instalado com o vagrant. O yarn tem muita melhor performance, incluindo network requests, tem modo offline e é na sua maioria compatível com o npm - coisas como npm install e npm clean cache são a mesma coisa só que com o comando yarn.

* Anúncio da coisa https://code.facebook.com/posts/1840075619545360
* https://yarnpkg.com/en

**Comment by rui1974** [comment]
André, já que amanhã há aula no horário normal, vou ver se ha consenso em relação a isso e incluo na vagrant se quiserem

**Comment by secprog** [comment]
Eu acho que existe consenso. Não sei a opinião do grupo de Frontent mas também acredito que aceitem.
Por isso a meu ver podem já começar a pré investigar a inclusão.

**Comment by secprog** [comment]
Quando puderes @rui1974 trata disto, basta incluíres no vagrantfile para quem quiser usar.
O issue já está aberto à mais de 1 mês e já podia estar resolvido.

**Comment by rui1974** [comment]
peço desculpa, passou-me completamente

**Comment by secprog** [comment]
Fixed with commit https://github.com/iptomar/projectary-api/commit/611b11597bc7a0cb1081ce7aa930bd8910d1ea49
